# Generated by Django 4.0 on 2023-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='demoNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
